### ISSUE TITLE
it return an error when repository is `owner/repoName`

### ISSUE THREAD

**Issue by bukinoshita** [bukinoshita/git-synced#8]
If repository field is like this: `"repository": "bukinoshita/git-synced"` it returns an error.

Before finding a repository [here](https://github.com/bukinoshita/git-synced/blob/master/index.js#L55) it should check if repo is a valid url, if it is it needs to prettify the url and then search.

- lib to validate if it's Git repo [is-github-repo](https://github.com/bukinoshita/is-github-repo) (it return a `type`, if returns a `type: repo` it should prettify the url.
- lib to prettify git url: [git-url-prettify](https://github.com/bukinoshita/git-url-prettify)

**Comment by ddg00** [comment]
i would love to solve this issue, can i take it ?

**Comment by bukinoshita** [comment]
hey @ddg00, thanks for you contribution. After a few tests here, I just realized that I created a wrong issue.
